
name: Release

on:
  release:
    types: [published]

jobs:
  release_zip_file:
    name: Prepare release asset
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Get version
        id: version
        uses: home-assistant/actions/helpers/version@master

      - name: "Set version number"
        run: |
          sed -i '/INTEGRATION_VERSION: Final = /c\INTEGRATION_VERSION: Final = "${{ steps.version.outputs.version }}"' ${{ github.workspace }}/custom_components/nswcovid/const.py
          python3 ${{ github.workspace }}/manage/update_manifest.py --version ${{ steps.version.outputs.version }}

      # Pack the NSWCovid dir as a zip and upload to the release
      - name: ZIP NSWCovid Dir
        run: |
          cd ${{ github.workspace }}/custom_components/nswcovid
          zip nswcovid.zip -r ./
      - name: Upload zip to release
        uses: svenstaro/upload-release-action@v1-release

        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ${{ github.workspace }}/custom_components/nswcovid/nswcovid.zip
          asset_name: nswcovid.zip
          tag: ${{ github.ref }}
          overwrite: true
